#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _CaBK_reg();
extern void _CaDynamics_reg();
extern void _Ca_HVA_reg();
extern void _Ca_LVA_reg();
extern void _Cagk_BC_reg();
extern void _IA_OLM_reg();
extern void _Ih_reg();
extern void _Ih_OLM_reg();
extern void _Im_reg();
extern void _Im_v2_reg();
extern void _K_P_reg();
extern void _K_T_reg();
extern void _Kd_reg();
extern void _Kv2like_reg();
extern void _Kv3_1_reg();
extern void _LcaMig_reg();
extern void _LcaMigCA3_reg();
extern void _Lca_BC_reg();
extern void _Lca_OLM_reg();
extern void _NaTa_reg();
extern void _NaTs_reg();
extern void _NaV_reg();
extern void _Nap_reg();
extern void _SK_reg();
extern void _bg2pyr_reg();
extern void _bg2pyr2_reg();
extern void _bgka_reg();
extern void _bgkaCA3_reg();
extern void _borgkaCA3_reg();
extern void _borgka_BC_reg();
extern void _catCA3_reg();
extern void _cat_OLM_reg();
extern void _ccanl_reg();
extern void _ccanlCA3_reg();
extern void _ccanl_BC_reg();
extern void _ccanl_OLM_reg();
extern void _cell_im_reg();
extern void _cell_lca_reg();
extern void _cell_nca_reg();
extern void _gskch_reg();
extern void _gskchCA3_reg();
extern void _gskch_BC_reg();
extern void _h_reg();
extern void _ichan2_reg();
extern void _ichan2CA3_reg();
extern void _ichan2_BC_reg();
extern void _ichan2_OLM_reg();
extern void _inter2emo_reg();
extern void _izh_reg();
extern void _mossy_reg();
extern void _nca_reg();
extern void _ncaCA3_reg();
extern void _nca_BC_reg();
extern void _pyr2emo_reg();
extern void _pyr2pyr_reg();
extern void _sahp_OLM_reg();
extern void _synapse_inter2pyr_reg();
extern void _vecevent_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," CaBK.mod");
fprintf(stderr," CaDynamics.mod");
fprintf(stderr," Ca_HVA.mod");
fprintf(stderr," Ca_LVA.mod");
fprintf(stderr," Cagk_BC.mod");
fprintf(stderr," IA_OLM.mod");
fprintf(stderr," Ih.mod");
fprintf(stderr," Ih_OLM.mod");
fprintf(stderr," Im.mod");
fprintf(stderr," Im_v2.mod");
fprintf(stderr," K_P.mod");
fprintf(stderr," K_T.mod");
fprintf(stderr," Kd.mod");
fprintf(stderr," Kv2like.mod");
fprintf(stderr," Kv3_1.mod");
fprintf(stderr," LcaMig.mod");
fprintf(stderr," LcaMigCA3.mod");
fprintf(stderr," Lca_BC.mod");
fprintf(stderr," Lca_OLM.mod");
fprintf(stderr," NaTa.mod");
fprintf(stderr," NaTs.mod");
fprintf(stderr," NaV.mod");
fprintf(stderr," Nap.mod");
fprintf(stderr," SK.mod");
fprintf(stderr," bg2pyr.mod");
fprintf(stderr," bg2pyr2.mod");
fprintf(stderr," bgka.mod");
fprintf(stderr," bgkaCA3.mod");
fprintf(stderr," borgkaCA3.mod");
fprintf(stderr," borgka_BC.mod");
fprintf(stderr," catCA3.mod");
fprintf(stderr," cat_OLM.mod");
fprintf(stderr," ccanl.mod");
fprintf(stderr," ccanlCA3.mod");
fprintf(stderr," ccanl_BC.mod");
fprintf(stderr," ccanl_OLM.mod");
fprintf(stderr," cell_im.mod");
fprintf(stderr," cell_lca.mod");
fprintf(stderr," cell_nca.mod");
fprintf(stderr," gskch.mod");
fprintf(stderr," gskchCA3.mod");
fprintf(stderr," gskch_BC.mod");
fprintf(stderr," h.mod");
fprintf(stderr," ichan2.mod");
fprintf(stderr," ichan2CA3.mod");
fprintf(stderr," ichan2_BC.mod");
fprintf(stderr," ichan2_OLM.mod");
fprintf(stderr," inter2emo.mod");
fprintf(stderr," izh.mod");
fprintf(stderr," mossy.mod");
fprintf(stderr," nca.mod");
fprintf(stderr," ncaCA3.mod");
fprintf(stderr," nca_BC.mod");
fprintf(stderr," pyr2emo.mod");
fprintf(stderr," pyr2pyr.mod");
fprintf(stderr," sahp_OLM.mod");
fprintf(stderr," synapse_inter2pyr.mod");
fprintf(stderr," vecevent.mod");
fprintf(stderr, "\n");
    }
_CaBK_reg();
_CaDynamics_reg();
_Ca_HVA_reg();
_Ca_LVA_reg();
_Cagk_BC_reg();
_IA_OLM_reg();
_Ih_reg();
_Ih_OLM_reg();
_Im_reg();
_Im_v2_reg();
_K_P_reg();
_K_T_reg();
_Kd_reg();
_Kv2like_reg();
_Kv3_1_reg();
_LcaMig_reg();
_LcaMigCA3_reg();
_Lca_BC_reg();
_Lca_OLM_reg();
_NaTa_reg();
_NaTs_reg();
_NaV_reg();
_Nap_reg();
_SK_reg();
_bg2pyr_reg();
_bg2pyr2_reg();
_bgka_reg();
_bgkaCA3_reg();
_borgkaCA3_reg();
_borgka_BC_reg();
_catCA3_reg();
_cat_OLM_reg();
_ccanl_reg();
_ccanlCA3_reg();
_ccanl_BC_reg();
_ccanl_OLM_reg();
_cell_im_reg();
_cell_lca_reg();
_cell_nca_reg();
_gskch_reg();
_gskchCA3_reg();
_gskch_BC_reg();
_h_reg();
_ichan2_reg();
_ichan2CA3_reg();
_ichan2_BC_reg();
_ichan2_OLM_reg();
_inter2emo_reg();
_izh_reg();
_mossy_reg();
_nca_reg();
_ncaCA3_reg();
_nca_BC_reg();
_pyr2emo_reg();
_pyr2pyr_reg();
_sahp_OLM_reg();
_synapse_inter2pyr_reg();
_vecevent_reg();
}
